language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3
install:
  - pip install --upgrade pytest
  - pip install --upgrade pytest-cov
  - pip install --upgrade coveralls
script:
  - py.test --cov-report= --cov=ssh-audit -v test
after_success:
  - coveralls

